# Generated by Django 3.1.7 on 2021-03-10 05:57

from django.db import migrations, models
import django.utils.timezone
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=100)),
                ('img', models.ImageField(default='uploads\\product-1.jpg', upload_to=shop.models.get_image_path)),
                ('on_sale', models.BooleanField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=20, null=True)),
                ('percent_off', models.DecimalField(blank=True, decimal_places=1, max_digits=30, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True)),
                ('bought_counter', models.DecimalField(decimal_places=0, default=0, max_digits=30)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
